import { useEffect, useRef } from "react";
import { useStore } from "../store/useStore";
import { useShallow } from "zustand/react/shallow";
import { fetchTokenUsage, resetTokenUsage } from "../lib/api";
import { Zap, RotateCcw } from "lucide-react";

function fmt(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "M";
  if (n >= 1_000) return (n / 1_000).toFixed(1) + "k";
  return String(n);
}

export function TokenCounter() {
  const { tokenUsage, setTokenUsage, resetTokenUsage: resetStore } = useStore(
    useShallow((s) => ({ tokenUsage: s.tokenUsage, setTokenUsage: s.setTokenUsage, resetTokenUsage: s.resetTokenUsage }))
  );
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Poll token usage every 10 seconds, only when tab is visible
  useEffect(() => {
    const poll = () => {
      if (!document.hidden) {
        fetchTokenUsage().then(setTokenUsage).catch(() => {});
      }
    };
    poll();
    intervalRef.current = setInterval(poll, 10_000);

    const onVisChange = () => {
      if (!document.hidden) poll();
    };
    document.addEventListener("visibilitychange", onVisChange);

    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
      document.removeEventListener("visibilitychange", onVisChange);
    };
  }, []);

  const handleReset = async () => {
    await resetTokenUsage().catch(() => {});
    resetStore();
  };

  const { prompt_tokens, completion_tokens, total_tokens, requests } = tokenUsage;

  return (
    <div className="flex items-center gap-2 px-2.5 py-1 bg-background border border-border rounded-lg text-xs font-mono">
      <Zap className="w-3 h-3 text-warning shrink-0" />

      <div className="flex items-center gap-2.5 divide-x divide-border">
        {/* Prompt */}
        <div className="flex items-center gap-1" title="Prompt tokens sent to LLM">
          <span className="text-muted">in</span>
          <span className="text-accent font-semibold">{fmt(prompt_tokens)}</span>
        </div>

        {/* Completion */}
        <div className="flex items-center gap-1 pl-2.5" title="Completion tokens generated by LLM">
          <span className="text-muted">out</span>
          <span className="text-success font-semibold">{fmt(completion_tokens)}</span>
        </div>

        {/* Total */}
        <div className="flex items-center gap-1 pl-2.5" title="Total tokens used">
          <span className="text-muted">total</span>
          <span className="text-foreground font-semibold">{fmt(total_tokens)}</span>
        </div>

        {/* Requests */}
        <div className="flex items-center gap-1 pl-2.5" title="Number of LLM requests made">
          <span className="text-muted">req</span>
          <span className="text-purple font-semibold">{requests}</span>
        </div>
      </div>

      {/* Reset button */}
      <button
        onClick={handleReset}
        title="Reset token counters"
        aria-label="Reset token counters"
        className="ml-1 text-muted-dim hover:text-muted transition-colors"
      >
        <RotateCcw className="w-3 h-3" />
      </button>
    </div>
  );
}
