"""
Tests for modbus/simulator.py — waveform dispatch, exception injection rules,
and SimulatorManager helper methods.

These tests exercise the manager and session logic directly without starting
an actual TCP server.
"""
from __future__ import annotations

import time
from unittest.mock import MagicMock, patch

import pytest

# conftest.py adds the backend root to sys.path
from modbus.register_maps import RegisterDef
from modbus.simulator import (
    SimulatorManager,
    SimulatorSession,
    _build_register_block,
    simulator_manager,
)
from modbus.waveforms import Ramp, SineWave


# ── Helpers ────────────────────────────────────────────────────────────────────

def _make_reg(address: int = 0) -> RegisterDef:
    """Return a minimal uint16 RegisterDef."""
    return RegisterDef(
        address=address,
        name="test_reg",
        unit="units",
        scale=1.0,
        data_type="uint16",
        access="ro",
        min_val=0.0,
        max_val=1000.0,
    )


def _make_session(manager: SimulatorManager, sid: str = "test01") -> SimulatorSession:
    """Inject a SimulatorSession directly into manager without starting a server."""
    session = SimulatorSession(
        session_id=sid,
        label=f"sim-{sid}",
        host="127.0.0.1",
        port=5099,
        unit_id=1,
        registers=[_make_reg(0), _make_reg(10)],
    )
    manager._sessions[sid] = session
    return session


# ── Tests ──────────────────────────────────────────────────────────────────────

class TestSetWaveform:
    def test_set_waveform_returns_true_for_existing_session(self):
        mgr = SimulatorManager()
        _make_session(mgr, "s1")
        waveform = SineWave(amplitude=500, period_s=60, dc_offset=500)
        result = mgr.set_waveform("s1", addr=0, waveform=waveform)
        assert result is True

    def test_set_waveform_returns_false_for_unknown_session(self):
        mgr = SimulatorManager()
        waveform = SineWave(amplitude=100, period_s=30, dc_offset=100)
        result = mgr.set_waveform("does_not_exist", addr=0, waveform=waveform)
        assert result is False

    def test_set_waveform_registers_waveform_used_in_build_register_block(self):
        """_build_register_block must return the waveform's tick() value for the
        registered address instead of the default sine+noise value."""
        mgr = SimulatorManager()
        session = _make_session(mgr, "s2")

        # Use a Ramp that always starts at a deterministic value (1234)
        ramp = Ramp(start=1234, step=1, min_val=0, max_val=65535)
        mgr.set_waveform("s2", addr=0, waveform=ramp)

        # Build a register block passing the session's waveforms
        t = time.time()
        block = _build_register_block(session.registers, t, session._waveforms)

        # Address 0 must equal the ramp's first tick (1234)
        assert block[0] == 1234

    def test_set_waveform_only_overrides_registered_address(self):
        """Addresses without a waveform still use the default generator."""
        mgr = SimulatorManager()
        session = _make_session(mgr, "s3")

        # Register waveform only for address 0
        fixed = SineWave(amplitude=0, period_s=60, dc_offset=5000)
        mgr.set_waveform("s3", addr=0, waveform=fixed)

        t = 0.0
        block = _build_register_block(session.registers, t, session._waveforms)

        # Address 0 must be 5000 (dc_offset, zero amplitude)
        assert block[0] == 5000
        # Address 10 must be present and generated by default logic (not 5000)
        assert 10 in block


class TestSetExceptionRule:
    def test_set_exception_rule_returns_true_for_existing_session(self):
        mgr = SimulatorManager()
        _make_session(mgr, "e1")
        result = mgr.set_exception_rule("e1", addr=0, exception_code=2, rate=0.5)
        assert result is True

    def test_set_exception_rule_returns_false_for_unknown_session(self):
        mgr = SimulatorManager()
        result = mgr.set_exception_rule("no_such_session", addr=0, exception_code=2, rate=0.5)
        assert result is False

    def test_set_exception_rule_stores_rule_in_session(self):
        mgr = SimulatorManager()
        session = _make_session(mgr, "e2")
        mgr.set_exception_rule("e2", addr=10, exception_code=3, rate=0.75)
        assert 10 in session.exception_rules
        exc_code, rate = session.exception_rules[10]
        assert exc_code == 3
        assert pytest.approx(rate) == 0.75

    def test_set_exception_rule_rate_zero_removes_rule(self):
        mgr = SimulatorManager()
        session = _make_session(mgr, "e3")
        # First set a rule
        mgr.set_exception_rule("e3", addr=0, exception_code=2, rate=0.9)
        assert 0 in session.exception_rules
        # Then disable it with rate=0.0
        mgr.set_exception_rule("e3", addr=0, exception_code=2, rate=0.0)
        assert 0 not in session.exception_rules


class TestSessionDefaults:
    def test_waveforms_and_exception_rules_initialized_empty(self):
        session = SimulatorSession(
            session_id="init_test",
            label="test",
            host="127.0.0.1",
            port=5099,
            unit_id=1,
            registers=[_make_reg(0)],
        )
        assert session._waveforms == {}
        assert session.exception_rules == {}

    def test_response_delay_ms_defaults_to_zero(self):
        session = SimulatorSession(
            session_id="delay_test",
            label="test",
            host="127.0.0.1",
            port=5099,
            unit_id=1,
            registers=[_make_reg(0)],
        )
        assert session.response_delay_ms == 0.0

    def test_response_delay_ms_field_exists_and_propagates_to_dict(self):
        session = SimulatorSession(
            session_id="delay_dict",
            label="test",
            host="127.0.0.1",
            port=5099,
            unit_id=1,
            registers=[_make_reg(0)],
            response_delay_ms=25.0,
        )
        d = session.to_dict()
        assert d["response_delay_ms"] == 25.0
